### PR TITLE
Unify marker like inconsistency about "，" and ", " in zh-Hant-TW

### PR DESCRIPTION
**Pull request by Nowar**
This is a minor improvement to unify UI feeling on markers, which can be regard as following work on #21.
Thanks~

(This my first time to use github PR feature, no idea my action correct or not,
please use cherry-pick or something else if I mess up the history?)

### CODE REVIEW

**Comment by mikezliu** [comment]
For punctuation like 「，。：」- I checked some Taiwanese websites and it seemed to show up like that (such as https://www.boca.gov.tw/cp-56-6862-98004-1.html) - do you know what's the difference with 「,.:」?

**Comment by mikezliu** [comment]
> (This my first time to use github PR feature, no idea my action correct or not,
> please use cherry-pick or something else if I mess up the history?)

Yeah you're using it correctly, don't worry about it since this is a non-code branch. Normally I should approve the PR and it can be merged after, but for this branch I tend to commit some parts of the PR first if other parts need discussion.

**Comment by Nowar** [comment]
> For punctuation like 「，。：」- I checked some Taiwanese websites and it seemed to show up like that (such as https://www.boca.gov.tw/cp-56-6862-98004-1.html) - do you know what's the difference with 「,.:」?
This is a style mixing challenge (both correct) that I want to unify.
Semantically, totally the same between 2-byte and 1-byte marker at all if they are respectively.
Usually we use。 at last position of the sentence, and，for sentence break, and、for several same-level enumerations, just like English.

For full-Chinese content (with little Eng, maybe), we all use full 2-byte markers, like ，。！？ since they are same width as other words. Ex: 你和我，他和她。誰在寫程式呢？太神奇了！

For full-Chinese content, we see nowhere that mixing 1-byte or 2-byte markers. All using 2-byte ones.

But in mixed English (default) - Chinese (local) app UI, that depends on authors.
Since some people may think 2-byte marker is strange mixing with English 1-byte markers.
For example,
This is a long-wording feature. It contains A, B, C.... (If you want some help, please call me!)
下一個是個翻譯過的功能。他包含 A、B、C ... （如果您遇到任何問題，請打給我！）
The mixed width difference may cause UX not so pretty, so 
I suggest all Chinese markers should unify to 1-byte or 2-byte for vision consistency.

No 50-50 Eng-Chinese article occurs (usually 80-20 or 90-10), so the difference is if we want to follow only 1 single style, or we want to be more local?

(I chose the former for Eng-Ch mixed mode. If you think the latter is better, I'm willing to contribute another patch instead that unifying all 1-byte markers within zh-Hant-TW to 2-byte.)
I'd happy to help.

**Comment by Nowar** [comment]
> > For punctuation like 「，。：」- I checked some Taiwanese websites and it seemed to show up like that (such as https://www.boca.gov.tw/cp-56-6862-98004-1.html) - do you know what's the difference with 「,.:」?
> > This is a style mixing challenge (both correct) that I want to unify.
> > Semantically, totally the same between 2-byte and 1-byte marker at all if they are respectively.
> > Usually we use。 at last position of the sentence, and，for sentence break, and、for several same-level enumerations, just like English.
> 
> For full-Chinese content (with little Eng, maybe), we all use full 2-byte markers, like ，。！？ since they are same width as other words. Ex: 你和我，他和她。誰在寫程式呢？太神奇了！
> 
> For full-Chinese content, we see nowhere that mixing 1-byte or 2-byte markers. All using 2-byte ones.
> 
> But in mixed English (default) - Chinese (local) app UI, that depends on authors. Since some people may think 2-byte marker is strange mixing with English 1-byte markers. For example, This is a long-wording feature. It contains A, B, C.... (If you want some help, please call me!) 下一個是個翻譯過的功能。他包含 A、B、C ... （如果您遇到任何問題，請打給我！） The mixed width difference may cause UX not so pretty, so I suggest all Chinese markers should unify to 1-byte or 2-byte for vision consistency.
> 
> No 50-50 Eng-Chinese article occurs (usually 80-20 or 90-10), so the difference is if we want to follow only 1 single style, or we want to be more local?
> 
> (I chose the former for Eng-Ch mixed mode. If you think the latter is better, I'm willing to contribute another patch instead that unifying all 1-byte markers within zh-Hant-TW to 2-byte.) I'd happy to help.

BTW, the space between Eng-Chinese is the same challenge too.
歡迎加入 Premium 會員等級。
歡迎加入Premium會員等級。
In real words, both occurs depending on authors pretty-sense.

These challenges are not important in today world, since most scenario mix different languages,
and the old-traditional format rules are not so important.
So all about consistency: You choose one style in your app, and all places follow.

You can checkout this article to see the Eng-Ch-mixing usage: https://www.ptt.cc/bbs/Foreign_Inv/M.1691768096.A.3A2.html

Note: The page you quote is our official national website, but it has minor difference than old-traditionaly chinese, like 
頭獎：5000元Benefit Xpress福利即享券(2名)
       ^^ 2-byte (traditional)                    ^ 1-byte, inconsistency, and no space

**Comment by mikezliu** [comment]
OK got it, thanks for the explanation! Let me do some reading and get back to you

**Comment by Nowar** [comment]
Quick link:
This is the spec of traditional Chinese: all 2-byte markers. FYI
https://language.moe.gov.tw/001/upload/files/site_content/m0001/hau/haushou.htm

**Comment by mikezliu** [comment]
If following 2-byte strictly, does it mean that 「歡迎加入 Premium 會員等級。」is supposed to be 「歡迎加入 P r e m i u m 會員等級。」?

I think using mixed mode 1-byte and 2-bytes is okay, since we don't show 2-byte for everything in the app (such as quote symbols).

**Comment by mikezliu** [comment]
Related: https://github.com/mystocksportfolio/translations/issues/18

**Comment by Nowar** [comment]
>

**Comment by Nowar** [comment]
> If following 2-byte strictly, does it mean that 「歡迎加入 Premium 會員等級。」is supposed to be 「歡迎加入 P r e m i u m 會員等級。」?
Well, in traditional zh-TW rules, it didn't consider the foreign language.

However, in real world, most people using the 1-byte for Eng.
So, I think the answer is no.

Example articles in Tech and Financial, FYI.
https://www.facebook.com/JservFans/posts/pfbid0DXT6sxhbfPi3EvavX7tFaGBsgFxZ5i7B7pRS25yMfRLDyujdh77TiCFyawtvtGzhl
https://hk.investing.com/news/forex-news/article-371271?dicbo=v2-2Jvqd1r

**Comment by mikezliu** [comment]
Hi @Nowar - do you still want to make this change? I haven't merged the commit yet

What do you think looks better for a localized app? From the links it seems like for mixed usage they use 2-byte punctuation like 「，。：」 with 1-byte for English characters so I'd lean towards doing that if it looks better. Adding @chiahsien as well in case he has any thoughts.

**Comment by Nowar** [comment]
I think I'll recreate a PR that using 2-byte Chinese punctuation and 1-byte English within Chinese sentence later.

Thanks for your reply!

**Comment by mikezliu** [comment]
OK sounds good!

**Pull request closed without merging**
